#!/bin/sh
# Lays out a release of the OID4VCWallet Swift package for
# github.com/IDFoundry/OID4VCgo-wallet-swift, which SwiftPM fetches it
# from: builds the release XCFramework (never the mobiletest build),
# zips it as the release asset, and writes the package's sources and a
# Package.swift naming that asset by URL and checksum. Before writing
# the URL manifest, it builds the package against the zipped framework
# for macOS and the iOS Simulator.
#
#   ./package-swift-release.sh VERSION PACKAGE_DIR ASSET_DIR
#
# VERSION is the Swift package's own version (1.2.3, no "v"), which the
# release is tagged with; PACKAGE_DIR is a checkout of the package
# repository; Mobile.xcframework.zip is written to ASSET_DIR.
# SKIP_FRAMEWORK_BUILD=1 reuses an existing build/release framework.
set -eu
[ $# -eq 3 ] || { echo "usage: $0 VERSION PACKAGE_DIR ASSET_DIR" >&2; exit 2; }
VERSION="$1"
PKG="$(cd "$2" && pwd)"
mkdir -p "$3"
ASSETS="$(cd "$3" && pwd)"
REPO="${OID4VC_WALLET_SWIFT_REPO:-IDFoundry/OID4VCgo-wallet-swift}"
echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$' || { echo "not a version: $VERSION" >&2; exit 2; }
cd "$(dirname "$0")"
HERE="$PWD"

if [ "${SKIP_FRAMEWORK_BUILD:-}" != 1 ]; then
    ../build-xcframework.sh
fi
FRAMEWORK=../build/release/Mobile.xcframework
[ -d "$FRAMEWORK" ] || { echo "no $FRAMEWORK" >&2; exit 1; }

ZIP="$ASSETS/Mobile.xcframework.zip"
rm -f "$ZIP"
(cd "$(dirname "$FRAMEWORK")" && ditto -c -k --sequesterRsrc --keepParent Mobile.xcframework "$ZIP")
CHECKSUM="$(swift package compute-checksum "$ZIP")"

rm -rf "$PKG/Sources"
mkdir -p "$PKG/Sources"
cp -R OID4VCWallet/Sources/OID4VCWallet "$PKG/Sources/OID4VCWallet"

manifest() { # $1: the binary target's source
    cat <<MANIFEST
// swift-tools-version:6.0
// Generated by OID4VCgo's mobile/ios/package-swift-release.sh: edit it
// there. Mobile.xcframework is OID4VCgo's Go wallet (the Go "mobile"
// package), built with gomobile; OID4VCWallet is its Swift API.
import PackageDescription

let package = Package(
    name: "OID4VCWallet",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [.library(name: "OID4VCWallet", targets: ["OID4VCWallet"])],
    targets: [
        $1,
        .target(name: "OID4VCWallet", dependencies: ["Mobile"]),
    ]
)
MANIFEST
}

# Build the package as published, against the zipped framework.
CHECK="$(mktemp -d)"
trap 'rm -rf "$CHECK"' EXIT
cp -R "$PKG/Sources" "$CHECK/"
(cd "$CHECK" && ditto -x -k "$ZIP" .)
manifest '.binaryTarget(name: "Mobile", path: "Mobile.xcframework")' > "$CHECK/Package.swift"
(cd "$CHECK" && swift build -q)
(cd "$CHECK" && xcodebuild build -scheme OID4VCWallet -destination 'generic/platform=iOS Simulator' -quiet)

manifest ".binaryTarget(name: \"Mobile\", url: \"https://github.com/$REPO/releases/download/$VERSION/Mobile.xcframework.zip\", checksum: \"$CHECKSUM\")" > "$PKG/Package.swift"
cd "$HERE/.."
echo "OID4VCWallet $VERSION: ABI $(sed -n 's/^const ABIVersion = //p' mobile.go), Mobile.xcframework.zip $CHECKSUM"
