#!/bin/sh
# Lays out a release of the OID4VCWallet Swift package for
# github.com/IDFoundry/OID4VCgo-wallet-swift, which SwiftPM fetches it
# from: builds the release XCFramework (never the mobiletest build),
# zips it as the release asset, and writes the package's sources, its
# README and a Package.swift naming that asset by URL and checksum.
# Before writing the URL manifest, it builds the package against the
# zipped framework for macOS and the iOS Simulator, with the README's
# example (ReadmeExample.swift) as a target of its own, so the example
# compiles against the release.
#
#   ./package-swift-release.sh VERSION PACKAGE_DIR ASSET_DIR
#
# VERSION is the Swift package's own version (1.2.3, no "v"), which the
# release is tagged with; PACKAGE_DIR is a checkout of the package
# repository; Mobile.xcframework.zip is written to ASSET_DIR.
# SKIP_FRAMEWORK_BUILD=1 reuses an existing build/release framework.
set -eu
[ $# -eq 3 ] || { echo "usage: $0 VERSION PACKAGE_DIR ASSET_DIR" >&2; exit 2; }
VERSION="$1"
PKG="$(cd "$2" && pwd)"
mkdir -p "$3"
ASSETS="$(cd "$3" && pwd)"
REPO="${OID4VC_WALLET_SWIFT_REPO:-IDFoundry/OID4VCgo-wallet-swift}"
echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$' || { echo "not a version: $VERSION" >&2; exit 2; }
cd "$(dirname "$0")"
HERE="$PWD"

if [ "${SKIP_FRAMEWORK_BUILD:-}" != 1 ]; then
    ../build-xcframework.sh
fi
FRAMEWORK=../build/release/Mobile.xcframework
[ -d "$FRAMEWORK" ] || { echo "no $FRAMEWORK" >&2; exit 1; }
# Never publish the test build, whatever the directory holds: it carries
# an in-process test issuer and Verifier (TestEnv).
if grep -rqs MobileTestEnv "$FRAMEWORK"; then
    echo "$FRAMEWORK is the mobiletest build: rebuild it without SKIP_FRAMEWORK_BUILD" >&2
    exit 1
fi

ZIP="$ASSETS/Mobile.xcframework.zip"
rm -f "$ZIP"
(cd "$(dirname "$FRAMEWORK")" && ditto -c -k --sequesterRsrc --keepParent Mobile.xcframework "$ZIP")
CHECKSUM="$(swift package compute-checksum "$ZIP")"

rm -rf "$PKG/Sources"
mkdir -p "$PKG/Sources"
cp -R OID4VCWallet/Sources/OID4VCWallet "$PKG/Sources/OID4VCWallet"

manifest() { # $1: the binary target's source; $2: any further targets
    cat <<MANIFEST
// swift-tools-version:6.0
// Generated by OID4VCgo's mobile/ios/package-swift-release.sh: edit it
// there. Mobile.xcframework is OID4VCgo's Go wallet (the Go "mobile"
// package), built with gomobile; OID4VCWallet is its Swift API.
import PackageDescription

let package = Package(
    name: "OID4VCWallet",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [.library(name: "OID4VCWallet", targets: ["OID4VCWallet"])],
    targets: [
        $1,
        .target(name: "OID4VCWallet", dependencies: ["Mobile"]),${2:-}
    ]
)
MANIFEST
}

# Build the package as published, against the zipped framework.
CHECK="$(mktemp -d)"
trap 'rm -rf "$CHECK"' EXIT
cp -R "$PKG/Sources" "$CHECK/"
mkdir "$CHECK/Sources/ReadmeExample"
cp ReadmeExample.swift "$CHECK/Sources/ReadmeExample/"
(cd "$CHECK" && ditto -x -k "$ZIP" .)
manifest '.binaryTarget(name: "Mobile", path: "Mobile.xcframework")' '
        .target(name: "ReadmeExample", dependencies: ["OID4VCWallet"]),' > "$CHECK/Package.swift"
(cd "$CHECK" && swift build -q)
(cd "$CHECK" && xcodebuild build -scheme OID4VCWallet -destination 'generic/platform=iOS Simulator' -quiet)

manifest ".binaryTarget(name: \"Mobile\", url: \"https://github.com/$REPO/releases/download/$VERSION/Mobile.xcframework.zip\", checksum: \"$CHECKSUM\")" > "$PKG/Package.swift"
{
    sed "s/@VERSION@/$VERSION/" <<'README'
# OID4VCgo-wallet-swift

`OID4VCWallet`: the Swift package of [OID4VCgo](https://github.com/IDFoundry/OID4VCgo)'s
mobile wallet, for iOS 16+ and macOS 13+. It receives credentials over
OpenID4VCI 1.0 and presents them over OpenID4VP 1.0, under HAIP 1.0, with
SD-JWT VC and ISO mdoc credentials. OID4VCgo is OpenID Certified for
those roles. It also presents an mdoc to Safari's Digital Credentials API
(`org-iso-mdoc`, from an iOS document provider extension), and in person
over Bluetooth (ISO/IEC 18013-5), as the holder or as the reader.

The protocols run in OID4VCgo's Go code, compiled with gomobile into the
`Mobile` XCFramework this package links. Your app owns the keys, the
storage and the UI:
- **Keys:** `KeychainKeyStore` keeps them in the Secure Enclave. Holder
  keys can require Face ID to present.
- **Storage:** `FileCredentialStore` uses complete file protection and
  is excluded from backup.
- **Wallet Provider:** you implement `WalletProvider`, which attests the
  wallet.

## Install

```swift
.package(url: "https://github.com/IDFoundry/OID4VCgo-wallet-swift", from: "@VERSION@")
```

In-person presentation needs `NSBluetoothAlwaysUsageDescription` in your
app's Info.plist.

## Use

```swift
README
    cat ReadmeExample.swift
    cat <<'README'
```

Errors are `WalletError`s. Each has:
- a stable `code`
- the remote party's own OAuth code in `protocolError`, for example
  `invalid_grant` for a wrong PIN
- `isRetryable`
- a `localizedDescription` you can show the holder

## Documentation

- [OID4VCgo's `mobile/`](https://github.com/IDFoundry/OID4VCgo/tree/main/mobile):
  what each platform supports, in-person presentation, the Go side and
  its [ABI](https://github.com/IDFoundry/OID4VCgo/blob/main/mobile/ABI.md).
- [MOBILE.md](https://github.com/IDFoundry/OID4VCgo/blob/main/MOBILE.md):
  the design.
- [The demo wallet app](https://github.com/IDFoundry/OID4VCgo/tree/main/mobile/ios/DemoWallet):
  a complete app on this package, including the document provider.

## Contributing

This repository is generated: OID4VCgo's `wallet-swift-release`
workflow publishes every release here from
[`mobile/ios`](https://github.com/IDFoundry/OID4VCgo/tree/main/mobile/ios),
README included. Issues and pull requests belong in
[OID4VCgo](https://github.com/IDFoundry/OID4VCgo).

## License

MIT. See [LICENSE](LICENSE).
README
} > "$PKG/README.md"
cd "$HERE/.."
echo "OID4VCWallet $VERSION: ABI $(sed -n 's/^const ABIVersion = //p' mobile.go), Mobile.xcframework.zip $CHECKSUM"
